export const SUBJECTS = [
  { id: 'SUBJ-001', name: 'Daniel R. Okafor', position: 'Senior Systems Engineer',
    tier: 'T5', stage: 'ADJUDICATION', status: 'ACTION_REQUIRED', eligibility: 'INTERIM',
    riskScore: 78, fastTrack: false, flaggedGuidelines: ['F', 'B'], daysInStage: 41,
    cvEnrolled: true, openAlerts: 2 },
  { id: 'SUBJ-002', name: 'Marcus T. Bell', position: 'Logistics Coordinator',
    tier: 'T3', stage: 'CONTINUOUS_VETTING', status: 'NEEDS_REVIEW', eligibility: 'SECRET',
    riskScore: 64, fastTrack: false, flaggedGuidelines: ['J', 'G'], daysInStage: 9,
    cvEnrolled: true, openAlerts: 1 },
  { id: 'SUBJ-003', name: 'Priya N. Shah', position: 'Financial Analyst',
    tier: 'T3', stage: 'INVESTIGATION', status: 'CLEAR', eligibility: 'NONE',
    riskScore: 8, fastTrack: true, flaggedGuidelines: [], daysInStage: 22,
    cvEnrolled: false, openAlerts: 0 },
];

export const ALERTS = [
  { id: 'ALERT-101', subjectId: 'SUBJ-001', subjectName: 'Daniel R. Okafor',
    category: 'FINANCIAL', severity: 'HIGH', priorityScore: 82, state: 'NEW',
    receivedDate: '2026-06-20', provider: 'TransUnion',
    description: 'New collection account reported.',
    identityMatch: { confidence: 0.96, identifiers: [
      { field: 'Name', subjectValue: 'Daniel R. Okafor', recordValue: 'Daniel Okafor', match: true }] },
    threshold: { rule: 'Delinquent debt > $5,000', met: true, detail: 'Exceeds threshold.' },
    priorAdjudication: { previouslyAdjudicated: false, reference: null },
    documents: [{ title: 'TransUnion credit-file extract',
      url: 'documents/SUBJ-001/credit-extract-20260620.json' }] },
];

export const CASE_001 = {
  subject: { ...SUBJECTS[0], ssn: '923-04-4821', dob: '1988-03-14',
    placeOfBirth: 'Lagos, Nigeria', citizenship: 'United States (naturalized 2003)',
    nationality: 'American',
    gender: 'Male', race: 'Black or African American',
    height: "6' 1\"", weight: '205 lb', eyeColor: 'Brown', hairColor: 'Black',
    maritalStatus: 'Married', phone: '(703) 555-0142', email: 'd.okafor88@example.com',
    address: '1427 Birch Hollow Ct, Manassas, VA 20109',
    addressHistory: [
      { address: '1427 Birch Hollow Ct, Manassas, VA 20109',
        fromDate: '2019-08', toDate: null },
      { address: '7605 Sudley Rd Apt 214, Manassas, VA 20109',
        fromDate: '2014-06', toDate: '2019-08' },
    ],
    employmentHistory: [
      { employer: 'Sentinel Dynamics LLC', title: 'Senior Systems Engineer',
        address: '14840 Conference Center Dr Suite 300, Chantilly, VA 20151',
        fromDate: '2018-02', toDate: null },
      { employer: 'Praxis Federal Solutions', title: 'Systems Engineer',
        address: '11951 Freedom Dr Suite 900, Reston, VA 20190',
        fromDate: '2013-01', toDate: '2018-02' },
    ] },
  aiSummary: 'Significant unresolved financial concerns under Guideline F.',
  timeline: [
    { date: '2026-01-27', actor: 'S. Whitfield', role: 'Investigator',
      event: 'ROI transmitted', note: 'Financial issues flagged' },
  ],
  wholePerson: [
    { factor: 'Nature, extent, and seriousness of the conduct',
      assessment: 'Sustained delinquency; serious.',
      evidence: [
        { type: 'ALERT', ref: 'ALERT-101', label: 'New collection account alert' },
        { type: 'DOCUMENT', ref: 'documents/SUBJ-001/credit-extract-20260620.json',
          label: 'TransUnion credit-file extract' },
      ] },
    { factor: 'Frequency and recency of the conduct',
      assessment: 'Ongoing; newest alert June 2026.',
      evidence: [{ type: 'RECORD_CHECK', ref: 'Financial record checks',
        label: 'Financial record checks' }] },
  ],
  guidelines: [
    { code: 'F', name: 'Financial Considerations', severity: 'C',
      aiReasoning: 'AG ¶ 19(a) established by the credit record.',
      evidence: [{ provider: 'TransUnion', type: 'Credit report',
        description: '$47,300 delinquent across 5 accounts', date: '2026-03-15' }],
      disqualifiers: [{ code: 'AG ¶ 19(a)', description: 'Inability to satisfy debts',
        evidence: '$47,300 delinquent' }],
      mitigators: [{ code: 'AG ¶ 20(b)', description: 'Conditions beyond control',
        applicability: 'PARTIAL', reasoning: 'Job loss involuntary; no repayment since.' }],
      precedents: [{ caseNumber: '20-01001', outcome: 'DENIED', year: 2021,
        relevance: 'DOHA hearing decision involving Guideline F',
        sourceUrl: 'https://doha.example/2021-ISCR-Hearing-Decisions/FileId/111111/' }] },
  ],
  investigation: {
    recordChecks: [
      { item: 'Subject interview (ESI)', status: 'COMPLETE',
        provider: 'DCSA field operations', requestedDate: '2025-10-02',
        completedDate: '2025-11-19',
        scope: 'Enhanced subject interview covering financial issues',
        resultSummary: 'Subject understated total debt.', documentUrl: null },
      { item: 'Financial record checks', status: 'COMPLETE',
        provider: 'TransUnion', requestedDate: '2026-03-10',
        completedDate: '2026-03-15',
        scope: 'Tri-bureau credit re-check plus civil judgment search',
        resultSummary: '$47,300 delinquent across five accounts.',
        documentUrl: 'documents/SUBJ-001/credit-extract-20260620.json' },
      { item: 'Foreign contact expansion leads', status: 'PENDING',
        provider: 'DCSA field operations', requestedDate: '2026-02-01',
        completedDate: null, scope: 'Expanded lead on sibling employment',
        resultSummary: 'Lead open.', documentUrl: null },
    ],
    sf86Sections: [
      { section: 'Section 20A', title: 'Financial record - delinquencies',
        subjectReport: 'Two delinquent accounts totaling about $9,000',
        matchedResult: 'Five delinquent accounts totaling $47,300',
        discrepancy: true, providers: ['TransUnion', 'Equifax'], guideline: 'F' },
    ],
    interviews: [{ date: '2025-11-19', type: 'Enhanced Subject Interview',
      interviewer: 'S. Whitfield', summary: 'Subject understated debt total.' }],
    roiEntries: [{ date: '2026-01-27', investigator: 'S. Whitfield', item: 'Financial',
      text: 'Credit data establishes sustained delinquency.' }],
  },
  adjudication: {
    recommendation: { action: 'SOR', aiSuggested: true,
      rationale: 'Unmitigated F concerns with candor issues.' },
    sorDraft: 'STATEMENT OF REASONS (DRAFT) - Guideline F: …',
    decisions: [],
  },
  alerts: ALERTS,
  documents: [{ title: 'Report of Investigation (ROI)', type: 'ROI',
    description: 'T5 ROI transmitted 2026-01-27', url: 'documents/doha-record.json' }],
};
