// Authoritative sources the demo's content is derived from. URLs verified 2026-07-03.
export const REFS = {
  NCSC_POLICY: 'https://www.dni.gov/index.php/ncsc-how-we-work/ncsc-security-executive-agent/ncsc-policy',
  SEAD1: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD_1.pdf',
  SEAD2: 'https://www.dni.gov/files/NCSC/documents/Regulations/Security-Executive-Agent-Directive-2-20201005.pdf',
  SEAD3: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-3-Reporting-U.pdf',
  SEAD4: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-4-Adjudicative-Guidelines-U.pdf',
  SEAD5: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD_5.pdf',
  SEAD6: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-6-continuous%20evaluation-U.pdf',
  SEAD7: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-7_BI_ReciprocityU.pdf',
  SEAD9: 'https://www.dni.gov/files/NCSC/documents/Regulations/06-02-22_ODNI_Document_SEAD-9_22-00284_U_SIGNED-FINAL.pdf',
  FIS: 'https://www.dcsa.mil/Personnel-Vetting/Background-Investigations/',
  DCSA_CV: 'https://www.dcsa.mil/Personnel-Vetting/Continuous-Vetting/',
  DCSA_PV: 'https://www.dcsa.mil/Personnel-Vetting/',
  OPM_FORMS: 'https://www.opm.gov/forms/federal-investigation-forms/',
  SF85: 'https://www.opm.gov/forms/pdf_fill/sf85.pdf',
  SF85P: 'https://www.opm.gov/forms/pdf_fill/sf85p.pdf',
  SF86: 'https://www.opm.gov/forms/pdf_fill/sf86.pdf',
  DOHA: 'https://doha.ogc.osd.mil/',
  DOHA_DECISIONS: 'https://doha.ogc.osd.mil/Industrial-Security-Program/Industrial-Security-Clearance-Decisions/',
  SEAD8: 'https://www.odni.gov/files/NCSC/documents/Regulations/SEAD-8_Temporary_Eligibility_U.pdf',
  FPVG: 'https://www.dni.gov/files/NCSC/documents/Regulations/Federal_Personnel_Vetting_Guidelines_10FEB2022-15Jul22.pdf',
  TW_INDEX: 'https://assets.performance.gov/files/Trusted_Workforce_Policy_Index.pdf',
  DODI_520002: 'https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/520002p.pdf',
  // esd.whs.mil blocks non-browser requests (HTTP 403 to curl); loads in a browser.
  DODD_52206: 'https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodd/522006p.pdf',
  EO_12968: 'https://www.federalregister.gov/documents/1995/08/07/95-19654/access-to-classified-information',
  CFR_147: 'https://www.ecfr.gov/current/title-32/subtitle-A/chapter-I/subchapter-D/part-147',
  SUITABILITY: 'https://www.dcpas.osd.mil/sites/default/files/2021-04/Suitability_Guide_for_Employees.pdf',
  CDSE: 'https://www.cdse.edu/Training/Toolkits/',
  CDSE_PV: 'https://www.cdse.edu/Training/Toolkits/Personnel-Vetting-Toolkit/#personnel-vetting-policy',
  CDSE_ADJ: 'https://www.cdse.edu/Training/Toolkits/Adjudicator-Toolkit/',
  DOE_OHA: 'https://www.energy.gov/oha/office-hearings-and-appeals',
  DOE_OHA_CASES: 'https://www.energy.gov/oha/listings/security-cases',
};
