// Authoritative sources the demo's content is derived from. URLs verified 2026-07-03.
export const REFS = {
  SEAD3: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-3-Reporting-U.pdf',
  SEAD4: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-4-Adjudicative-Guidelines-U.pdf',
  SEAD6: 'https://www.dni.gov/files/NCSC/documents/Regulations/SEAD-6-continuous%20evaluation-U.pdf',
  FIS: 'https://www.dcsa.mil/Personnel-Vetting/Background-Investigations/',
  DCSA_CV: 'https://www.dcsa.mil/Personnel-Vetting/Continuous-Vetting/',
  DCSA_PV: 'https://www.dcsa.mil/Personnel-Vetting/',
  SF86: 'https://www.opm.gov/forms/pdf_fill/sf86.pdf',
  DOHA: 'https://doha.ogc.osd.mil/',
  DOHA_DECISIONS: 'https://doha.ogc.osd.mil/Industrial-Security-Program/Industrial-Security-Clearance-Decisions/',
  SEAD8: 'https://www.odni.gov/files/NCSC/documents/Regulations/SEAD-8_Temporary_Eligibility_U.pdf',
  FPVG: 'https://www.dni.gov/files/NCSC/documents/Regulations/Federal_Personnel_Vetting_Guidelines_10FEB2022-15Jul22.pdf',
  TW_INDEX: 'https://assets.performance.gov/files/Trusted_Workforce_Policy_Index.pdf',
  DODI_520002: 'https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/520002p.pdf',
  SUITABILITY: 'https://www.dcpas.osd.mil/sites/default/files/2021-04/Suitability_Guide_for_Employees.pdf',
  CDSE: 'https://www.cdse.edu/Training/Toolkits/',
  CDSE_PV: 'https://www.cdse.edu/Training/Toolkits/Personnel-Vetting-Toolkit/#personnel-vetting-policy',
  CDSE_ADJ: 'https://www.cdse.edu/Training/Toolkits/Adjudicator-Toolkit/',
  DOE_OHA: 'https://www.energy.gov/oha/office-hearings-and-appeals',
  DOE_OHA_CASES: 'https://www.energy.gov/oha/listings/security-cases',
};
